name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and deploy the Docker image
      run: |
        docker build -t udagram-api-feed ./udagram-api-feed
        docker tag udagram-api-feed 2bit2bit/udagram-api-feed

        docker build -t udagram-api-user ./udagram-api-user
        docker tag udagram-api-user 2bit2bit/udagram-api-user

        docker build -t udagram-frontend ./udagram-frontend
        docker tag udagram-frontend 2bit2bit/udagram-frontend

        docker build -t reverseproxy ./udagram-reverseproxy
        docker tag reverseproxy 2bit2bit/reverseproxy

        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push 2bit2bit/udagram-api-feed
        docker push 2bit2bit/udagram-api-user
        docker push 2bit2bit/udagram-frontend
        docker push 2bit2bit/reverseproxy


